<a href="https://colab.research.google.com/github/shagunsingla15-cloud/BIS-Standard-Recommendation-Engine/blob/main/Titanic_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
df.drop(['deck','embark_town','alive','class','who','adult_male'],axis = 1, inplace =True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [8]:
df['age'].fillna(df['age'].mean(),inplace =True)

/tmp/ipykernel_4391/1644344701.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace =True)

In [9]:
df.dropna(subset = ['embarked'],inplace = True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
df['sex']= le.fit_transform(df['sex'])
df['embarked']= le.fit_transform(df['embarked'])

In [13]:
df = df.astype(int)

In [14]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [15]:
X = df.drop('survived',axis = 1)
y = df['survived']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [18]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [20]:
accuracy_score(y_test, y_pred)

0.8163265306122449

In [21]:
confusion_matrix(y_test,y_pred)

array([[157,  27],
       [ 27,  83]])

In [22]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       184
           1       0.75      0.75      0.75       110

    accuracy                           0.82       294
   macro avg       0.80      0.80      0.80       294
weighted avg       0.82      0.82      0.82       294

# KNN

In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [24]:
x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.fit_transform(X_test)

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
knn_model = KNeighborsClassifier(n_neighbors =5)
knn_model.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [27]:
y_pred_knn = knn_model.predict(x_test_scaled)

In [28]:
accuracy_score(y_test, y_pred_knn)

0.8061224489795918

In [29]:
confusion_matrix(y_test, y_pred_knn)

array([[158,  26],
       [ 31,  79]])

In [30]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85       184
           1       0.75      0.72      0.73       110

    accuracy                           0.81       294
   macro avg       0.79      0.79      0.79       294
weighted avg       0.80      0.81      0.81       294

# naive bayes

In [31]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()

In [32]:
model_NB.fit(X_train,y_train)

GaussianNB()

In [33]:
y_pred_NB = model_NB.predict(X_test)

In [34]:
accuracy_score(y_test,y_pred_NB)

0.7789115646258503

In [35]:
confusion_matrix(y_test,y_pred_NB)

array([[145,  39],
       [ 26,  84]])

In [36]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.79      0.82       184
           1       0.68      0.76      0.72       110

    accuracy                           0.78       294
   macro avg       0.77      0.78      0.77       294
weighted avg       0.79      0.78      0.78       294

# Decision Tree

In [38]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
model_DT = DecisionTreeClassifier(random_state = 42)

In [40]:
model_DT.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [42]:
y_pred_DT = model_DT.predict(x_test_scaled)

In [43]:
accuracy_score(y_test, y_pred_DT)

0.7891156462585034

In [44]:
confusion_matrix(y_test, y_pred_DT)

array([[163,  21],
       [ 41,  69]])

In [45]:
print(classification_report(y_test, y_pred_DT))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84       184
           1       0.77      0.63      0.69       110

    accuracy                           0.79       294
   macro avg       0.78      0.76      0.77       294
weighted avg       0.79      0.79      0.78       294

# SVM

In [46]:
from sklearn.svm import SVC

In [49]:
model_svm = SVC(kernel = 'rbf')
model_svm.fit(x_train_scaled, y_train)

SVC()

In [51]:
y_pred_svm = model_svm.predict(x_test_scaled)

In [52]:
accuracy_score(y_test, y_pred_svm)

0.8197278911564626

In [53]:
confusion_matrix(y_test, y_pred_svm)

array([[160,  24],
       [ 29,  81]])

In [54]:
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86       184
           1       0.77      0.74      0.75       110

    accuracy                           0.82       294
   macro avg       0.81      0.80      0.81       294
weighted avg       0.82      0.82      0.82       294